// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)
